<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<AssemblyTitle>Xceed.Wpf.Words.Sample</AssemblyTitle>
		<AssemblyCompany>Logiciels Xceed</AssemblyCompany>
		<AssemblyProduct>Xceed.Wpf.Words.Sample</AssemblyProduct>
		<AssemblyCopyright>Copyright © 2024</AssemblyCopyright>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<LangVersion>11.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Xceed.Words.NET" Version="3.0.24152.1219" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="logox.ico"/>
	</ItemGroup>

</Project>
